[s3]
bucket = "wikidot-backup"

[wikidot]
sites = [
    "scptestwiki",
    "techcheck",
]

always-fetch-site = true

use-tls = [
    "scp-wiki",
    "techcheck",
]

use-admin-members-list = [
    "scp-wiki",
    "techcheck",
]
