[s3]
bucket = "wikidot-backup"

[wikidot]
sites = [
    "scp-wiki",
    "scptestwiki",
    "scpedia",
    "techcheck",
]

always-fetch-site = false

use-tls = [
    "scp-wiki",
    "techcheck",
]

use-admin-members-list = []
