[s3]
bucket = "wikidot-backup"

[wikidot]
sites = [
    "scp-int",
    "scp-en",
    "wl-en",
    "scp-zh-cn",
    "scp-fr",
    "scp-ru",
    "scp-pl",
    "scp-es",
    "scp-jp",
    "scp-ko",
    "scp-th",
    "scp-de",
    "scp-it",
    "scp-uk",
    "scp-pt",
    "scp-cs",
    "scp-zh-tw",
    "scp-vn",
    "scp-el",
    "scp-id",
    "scp-nd",
    "scp-tr",
    "scp-ar",
    "scp-cy",
    "scp-et",
    "scp-he",
    "scp-hu",
    "scp-jbo",
    "scp-nl",
    "scp-ro",
    "scp-sh",
    "scp-sl",
    "scp-la",
    "wl-pl",
    "wl-ja",
    "wl-cs",
    "wl-ko",
    "wl-vi",
    "o5-int",
    "o5-en",
    "o5-cn",
    "o5-fr",
    "o5-pl",
    "o5-es",
    "o5-th",
    "o5-jp",
    "o5-de",
    "o5-pt",
    "o5-cs",
    "o5-vn",
    "o5-el",
    "o5-nl",
    "o5-sl",
    "o5-wl-en",
    "backrooms-en",
    "backrooms-vn",
    "backrooms-pl",
    "backrooms-cn",
    "backrooms-fr",
    "backrooms-ru",
    "backrooms-pt",
    "backrooms-es",
    "backrooms-jp",
    "scp-int-sandbox",
    "scp-sandbox-1",
    "scp-sandbox-2",
    "scp-sandbox-3",
    "scpkrsandbox",
    "scpsandboxcn",
    "sandboxscpfr",
    "scpsandbox-pl",
    "borradores-scp-es",
    "borradores-scp-es-2",
    "scp-th-sandbox",
    "scp-jp-sandbox2",
    "scp-jp-sandbox3",
    "scp-jp-storage",
    "scpsandboxde",
    "scpsandboxit",
    "scpsandbox-ua",
    "scpsandboxbr",
    "scp-cs-sandbox",
    "scp-cs-sandbox-2",
    "scp-sandbox-zh",
    "scp-sandbox2-zh",
    "scpvnsandbox",
    "sandboxscp-el",
    "scp-id-sandbox",
    "scpvakfisandbox",
    "scpsandboxhu",
    "scpsandboxnl",
    "scp-sh-sandbox",
    "scp-sandbox-sl",
    "smlt",
    "topia",
    "kaktuskontainer",
    "scpdsandbox",
    "scptestwiki",
    "co-team",
    "mast-team",
    "scpclassic",
    "scpexplained",
    "brucebase",
]
