name: Python Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUFF_NO_CACHE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.dev.txt

      - name: MyPy
        run: mypy bzhr

      - name: Lints
        run: ruff check bzhr

      - name: Formatting
        run: ruff format --check bzhr
